var annotated_dup =
[
    [ "BitRef", "classBitRef.html", "classBitRef" ],
    [ "CAspirador", "classCAspirador.html", "classCAspirador" ],
    [ "CJogoDoGalo", "classCJogoDoGalo.html", "classCJogoDoGalo" ],
    [ "CJogoEmLinha", "classCJogoEmLinha.html", "classCJogoEmLinha" ],
    [ "CListaNo", "classCListaNo.html", "classCListaNo" ],
    [ "COitoDamas", "classCOitoDamas.html", "classCOitoDamas" ],
    [ "CParticao", "classCParticao.html", "classCParticao" ],
    [ "CProblemaArtificial", "classCProblemaArtificial.html", "classCProblemaArtificial" ],
    [ "CPuzzle8", "classCPuzzle8.html", "classCPuzzle8" ],
    [ "CTesteTVector", "classCTesteTVector.html", "classCTesteTVector" ],
    [ "SIndicador", "structSIndicador.html", "structSIndicador" ],
    [ "SIndice", "structSIndice.html", "structSIndice" ],
    [ "SJogoEmLinha", "structSJogoEmLinha.html", "structSJogoEmLinha" ],
    [ "SParametro", "structSParametro.html", "structSParametro" ],
    [ "SParametrosEspaco", "structSParametrosEspaco.html", "structSParametrosEspaco" ],
    [ "SResultado", "structSResultado.html", "structSResultado" ],
    [ "SValorEstado", "structSValorEstado.html", "structSValorEstado" ],
    [ "TCodificacaoArvore", "classTCodificacaoArvore.html", null ],
    [ "TCodificacaoBinaria", "classTCodificacaoBinaria.html", null ],
    [ "TCodificacaoInteira", "classTCodificacaoInteira.html", null ],
    [ "TCodificacaoPermutacao", "classTCodificacaoPermutacao.html", "classTCodificacaoPermutacao" ],
    [ "TCodificacaoReal", "classTCodificacaoReal.html", "classTCodificacaoReal" ],
    [ "TProcura", "classTProcura.html", "classTProcura" ],
    [ "TProcuraAdversa", "classTProcuraAdversa.html", "classTProcuraAdversa" ],
    [ "TProcuraConstrutiva", "classTProcuraConstrutiva.html", "classTProcuraConstrutiva" ],
    [ "TProcuraMelhorativa", "classTProcuraMelhorativa.html", "classTProcuraMelhorativa" ],
    [ "TVector", "classTVector.html", "classTVector" ]
];