var searchData=
[
  ['parâmetro_0',['Ação 4 - Ver a alterar um parâmetro',['../teste_aspirador1.html#autotoc_md42',1,'']]],
  ['parâmetros_1',['Ação 2: Menu 3 - Parâmetros',['../teste_tvector.html#autotoc_md89',1,'']]],
  ['parte_201_202_2',['Teste Aspirador - Parte 1/2',['../teste_aspirador1.html',1,'']]],
  ['parte_202_202_3',['Teste Aspirador - Parte 2/2',['../teste_aspirador2.html',1,'']]],
  ['particao_4',['Teste Particao',['../teste_particao.html',1,'']]],
  ['particao_20codificação_20binária_5',['Teste Particao - Codificação Binária',['../teste_particao_cb.html',1,'']]],
  ['pastas_6',['Estrutura de Pastas',['../index.html#autotoc_md8',1,'']]],
  ['permutação_7',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['poda_8',['Ação 6 - Torneio Poda',['../teste_jogo_em_linha.html#autotoc_md68',1,'']]],
  ['por_20permutação_9',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['primeiro_10',['primeiro',['../teste_aspirador2.html#autotoc_md50',1,'Ação 11 - Efetuar uma procura em Profundidade Primeiro'],['../teste_puzzle8.html#autotoc_md80',1,'Ação 6 - Melhor Primeiro']]],
  ['procura_20em_20largura_11',['procura em largura',['../teste_8damas.html#autotoc_md25',1,'Ação 3 - Procura em Largura'],['../teste_puzzle8.html#autotoc_md77',1,'Ação 3 - Procura em Largura'],['../teste_aspirador1.html#autotoc_md43',1,'Ação 5 - Efetuer uma procura em Largura'],['../teste_aspirador1.html#autotoc_md47',1,'Ação 9 - Desafio Procura em Largura']]],
  ['procura_20em_20profundidade_12',['procura em profundidade',['../teste_aspirador2.html#autotoc_md49',1,'Ação 10 - Procura em Profundidade'],['../teste_8damas.html#autotoc_md26',1,'Ação 4 - Procura em Profundidade'],['../teste_puzzle8.html#autotoc_md78',1,'Ação 4 - Procura em Profundidade']]],
  ['procura_20em_20profundidade_20primeiro_13',['Ação 11 - Efetuar uma procura em Profundidade Primeiro',['../teste_aspirador2.html#autotoc_md50',1,'']]],
  ['procura_20maior_14',['Ação 12 - Ver uma árvore de procura maior',['../teste_aspirador2.html#autotoc_md51',1,'']]],
  ['procura_20profundidade_15',['Ação 15 - Desafio Procura Profundidade',['../teste_aspirador2.html#autotoc_md54',1,'']]],
  ['profundidade_16',['profundidade',['../teste_aspirador2.html#autotoc_md49',1,'Ação 10 - Procura em Profundidade'],['../teste_aspirador2.html#autotoc_md54',1,'Ação 15 - Desafio Procura Profundidade'],['../teste_jogo_em_linha.html#autotoc_md65',1,'Ação 3 - Torneio Profundidade'],['../teste_8damas.html#autotoc_md26',1,'Ação 4 - Procura em Profundidade'],['../teste_puzzle8.html#autotoc_md78',1,'Ação 4 - Procura em Profundidade']]],
  ['profundidade_20ilimitada_17',['Ação 14 - Profundidade ilimitada',['../teste_aspirador2.html#autotoc_md53',1,'']]],
  ['profundidade_20iterativa_18',['Ação 13 - Profundidade Iterativa',['../teste_aspirador2.html#autotoc_md52',1,'']]],
  ['profundidade_20primeiro_19',['Ação 11 - Efetuar uma procura em Profundidade Primeiro',['../teste_aspirador2.html#autotoc_md50',1,'']]],
  ['projeto_20',['Sobre o Projeto',['../index.html#autotoc_md3',1,'']]],
  ['puzzle_208_21',['Teste Puzzle 8',['../teste_puzzle8.html',1,'']]]
];
