var searchData=
[
  ['parte_201_202_0',['Teste Aspirador - Parte 1/2',['../teste_aspirador1.html',1,'']]],
  ['parte_202_202_1',['Teste Aspirador - Parte 2/2',['../teste_aspirador2.html',1,'']]],
  ['partição_20largura_20primeiro_2',['Partição, largura primeiro',['../tutorial_particaolargura.html',1,'']]],
  ['partição_20profundidade_20primeiro_3',['Partição, profundidade primeiro',['../tutorial_particaoprof.html',1,'']]],
  ['particao_4',['Teste Particao',['../teste_particao.html',1,'']]],
  ['particao_20codificação_20binária_5',['Teste Particao - Codificação Binária',['../teste_particao_cb.html',1,'']]],
  ['pasta_20resultados_6',['pasta resultados',['../md_Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Adversa_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Melhorativa_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Construtiva_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados']]],
  ['permutação_7',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['por_20permutação_8',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['primeiro_9',['primeiro',['../tutorial_4damaslargura.html',1,'4 Damas, largura primeiro'],['../tutorial_4damasprof.html',1,'4 Damas, profundidade primeiro'],['../tutorial_particaolargura.html',1,'Partição, largura primeiro'],['../tutorial_particaoprof.html',1,'Partição, profundidade primeiro'],['../tutorial_puzzle8melhor.html',1,'Puzzle8, procura melhor primeiro']]],
  ['procura_20em_20largura_10',['Puzzle8, procura em largura',['../tutorial_puzzle8largura.html',1,'']]],
  ['procura_20em_20profundidade_20iterativa_11',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['procura_20em_20profundidade_20nível_203_12',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['procura_20melhor_20primeiro_13',['Puzzle8, procura melhor primeiro',['../tutorial_puzzle8melhor.html',1,'']]],
  ['procuras_20adversas_14',['Tutorial das procuras Adversas',['../tutorial_adversas.html',1,'']]],
  ['procuras_20adversas_20literatura_15',['procuras adversas literatura',['../tutorial_adversaslit.html',1,'Procuras Adversas - Literatura'],['../tutorial_adversas5c.html',1,'Procuras Adversas - Literatura'],['../tutorial_adversas5b.html',1,'Procuras Adversas - Literatura'],['../tutorial_adversas5a.html',1,'Procuras Adversas - Literatura']]],
  ['procuras_20adversas_20minimax_20com_20cortes_20alfa_20beta_16',['Procuras Adversas, MiniMax com cortes alfa/beta',['../tutorial_galoalfabeta.html',1,'']]],
  ['procuras_20construtivas_17',['Tutorial das procuras Construtivas',['../tutorial_construtivas.html',1,'']]],
  ['procuras_20melhorativas_18',['Tutorial das procuras Melhorativas',['../tutorial_melhorativas.html',1,'']]],
  ['profundidade_20iterativa_19',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['profundidade_20nível_203_20',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['profundidade_20primeiro_21',['profundidade primeiro',['../tutorial_4damasprof.html',1,'4 Damas, profundidade primeiro'],['../tutorial_particaoprof.html',1,'Partição, profundidade primeiro']]],
  ['puzzle_208_22',['Teste Puzzle 8',['../teste_puzzle8.html',1,'']]],
  ['puzzle8_20astar_23',['Puzzle8, AStar',['../tutorial_puzzle8astar.html',1,'']]],
  ['puzzle8_20bnb_24',['Puzzle8, BnB',['../tutorial_puzzle8bnb.html',1,'']]],
  ['puzzle8_20procura_20em_20largura_25',['Puzzle8, procura em largura',['../tutorial_puzzle8largura.html',1,'']]],
  ['puzzle8_20procura_20em_20profundidade_20iterativa_26',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['puzzle8_20procura_20em_20profundidade_20nível_203_27',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['puzzle8_20procura_20melhor_20primeiro_28',['Puzzle8, procura melhor primeiro',['../tutorial_puzzle8melhor.html',1,'']]]
];
