var searchData=
[
  ['parte_201_202_0',['Teste Aspirador - Parte 1/2',['../teste_aspirador1.html',1,'']]],
  ['parte_202_202_1',['Teste Aspirador - Parte 2/2',['../teste_aspirador2.html',1,'']]],
  ['partição_20largura_20primeiro_2',['Partição, largura primeiro',['../tutorial_particaolargura.html',1,'']]],
  ['partição_20profundidade_20primeiro_3',['Partição, profundidade primeiro',['../tutorial_particaoprof.html',1,'']]],
  ['particao_4',['Teste Particao',['../teste_particao.html',1,'']]],
  ['particao_20codificação_20binária_5',['Teste Particao - Codificação Binária',['../teste_particao_cb.html',1,'']]],
  ['pasta_20resultados_6',['pasta resultados',['../md_Construtiva_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Melhorativa_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados'],['../md_Adversa_2Teste_2Resultados_2README-Resultados.html',1,'Pasta Resultados']]],
  ['permutação_7',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['por_20permutação_8',['Teste 8 Damas - Codificação por Permutação',['../teste_8damas_cp.html',1,'']]],
  ['primeiro_9',['primeiro',['../tutorial_4damaslargura.html',1,'4 Damas, largura primeiro'],['../tutorial_4damasprof.html',1,'4 Damas, profundidade primeiro'],['../tutorial_particaolargura.html',1,'Partição, largura primeiro'],['../tutorial_particaoprof.html',1,'Partição, profundidade primeiro'],['../tutorial_puzzle8melhor.html',1,'Puzzle8, procura melhor primeiro']]],
  ['procura_20cega_10',['👓 Procuras Construtivas - Procura Cega',['../tutorial_construtivas3a.html',1,'']]],
  ['procura_20cega_20algoritmos_11',['👓 Procuras Construtivas - Procura Cega - Algoritmos',['../tutorial_construtivas3b.html',1,'']]],
  ['procura_20em_20largura_12',['Puzzle8, procura em largura',['../tutorial_puzzle8largura.html',1,'']]],
  ['procura_20em_20profundidade_20iterativa_13',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['procura_20em_20profundidade_20nível_203_14',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['procura_20informada_15',['👓 Procuras Construtivas - Procura Informada',['../tutorial_construtivas4a.html',1,'']]],
  ['procura_20melhor_20primeiro_16',['Puzzle8, procura melhor primeiro',['../tutorial_puzzle8melhor.html',1,'']]],
  ['procuras_20adversas_17',['Tutorial das Procuras Adversas',['../tutorial_adversas.html',1,'']]],
  ['procuras_20adversas_20introdução_18',['Procuras Adversas - Introdução',['../tutorial_adversas5a.html',1,'']]],
  ['procuras_20adversas_20jogo_20do_20galo_20minmax_19',['Procuras Adversas, Jogo do Galo, MinMax',['../tutorial_galominimax.html',1,'']]],
  ['procuras_20adversas_20literatura_20',['Procuras Adversas - Literatura',['../tutorial_adversaslit.html',1,'']]],
  ['procuras_20adversas_20minimax_21',['Procuras Adversas - MiniMax',['../tutorial_adversas5b.html',1,'']]],
  ['procuras_20adversas_20minimax_20com_20cortes_20alfa_20beta_22',['Procuras Adversas, MiniMax com cortes alfa/beta',['../tutorial_galoalfabeta.html',1,'']]],
  ['procuras_20adversas_20monte_20carlo_23',['Procuras Adversas - Monte Carlo',['../tutorial_adversas5c.html',1,'']]],
  ['procuras_20adversas_20teste_20jogo_20do_20galo_24',['Procuras Adversas, Teste Jogo do Galo',['../teste_jogo_do_galo.html',1,'']]],
  ['procuras_20adversas_20teste_20jogo_20em_20linha_25',['Procuras Adversas, Teste Jogo Em Linha',['../teste_jogo_em_linha.html',1,'']]],
  ['procuras_20cegas_26',['💻 Puzzle 8 - Procuras Cegas',['../teste_puzzle8.html',1,'']]],
  ['procuras_20construtivas_27',['Tutorial das Procuras Construtivas',['../tutorial_construtivas.html',1,'']]],
  ['procuras_20construtivas_20algoritmos_20cegos_28',['📖 Procuras Construtivas - Algoritmos Cegos',['../tutorial_construtivaslit.html',1,'']]],
  ['procuras_20construtivas_20algoritmos_20informados_29',['📖 Procuras Construtivas - Algoritmos Informados',['../tutorial_construtivaslit2.html',1,'']]],
  ['procuras_20construtivas_20procura_20cega_30',['👓 Procuras Construtivas - Procura Cega',['../tutorial_construtivas3a.html',1,'']]],
  ['procuras_20construtivas_20procura_20cega_20algoritmos_31',['👓 Procuras Construtivas - Procura Cega - Algoritmos',['../tutorial_construtivas3b.html',1,'']]],
  ['procuras_20construtivas_20procura_20informada_32',['👓 Procuras Construtivas - Procura Informada',['../tutorial_construtivas4a.html',1,'']]],
  ['procuras_20informadas_33',['💻 Puzzle 8 - Procuras Informadas',['../teste_puzzle8b.html',1,'']]],
  ['procuras_20melhorativas_34',['Tutorial das procuras Melhorativas',['../tutorial_melhorativas.html',1,'']]],
  ['profundidade_20iterativa_35',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['profundidade_20nível_203_36',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['profundidade_20primeiro_37',['profundidade primeiro',['../tutorial_4damasprof.html',1,'4 Damas, profundidade primeiro'],['../tutorial_particaoprof.html',1,'Partição, profundidade primeiro']]],
  ['puzzle_208_20procuras_20cegas_38',['💻 Puzzle 8 - Procuras Cegas',['../teste_puzzle8.html',1,'']]],
  ['puzzle_208_20procuras_20informadas_39',['💻 Puzzle 8 - Procuras Informadas',['../teste_puzzle8b.html',1,'']]],
  ['puzzle8_20astar_40',['Puzzle8, AStar',['../tutorial_puzzle8astar.html',1,'']]],
  ['puzzle8_20bnb_41',['Puzzle8, BnB',['../tutorial_puzzle8bnb.html',1,'']]],
  ['puzzle8_20procura_20em_20largura_42',['Puzzle8, procura em largura',['../tutorial_puzzle8largura.html',1,'']]],
  ['puzzle8_20procura_20em_20profundidade_20iterativa_43',['Puzzle8, procura em profundidade iterativa',['../tutorial_puzzle8iterativa.html',1,'']]],
  ['puzzle8_20procura_20em_20profundidade_20nível_203_44',['Puzzle8, procura em profundidade nível 3',['../tutorial_puzzle8prof.html',1,'']]],
  ['puzzle8_20procura_20melhor_20primeiro_45',['Puzzle8, procura melhor primeiro',['../tutorial_puzzle8melhor.html',1,'']]]
];
